name: Integration Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  application-tests:
    name: wp-env Application Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Run wp-env application tests
        run: npm run test:integration

      - name: Stop wp-env
        if: ${{ always() }}
        run: npm run wp-env:stop
